[Para Revisão] - 2. Syntax and Formatting
GDGDuqueDeCaxias/cssguideline-translate-ptbr pull request #10
Opened 2017-01-19 17:03 UTC by Lucasktrindade

2017-01-30 23:08 UTC, emanuelgsouza approved these changes

2017-01-31 00:55 UTC, gabrielclima requested changes
Acho que só teve um lance na tradução da expressão ali

2017-01-31 00:55 UTC, gabrielclima commented on chapters/2.Syntax-and-Formatting.md
> +Além disso, o código vai parecer limpo e dar a impresso de estar limpo. É um ecossistema muito melhor para se trabalhar, e faz com que outro membro da equipe mantenha o padrão de limpeza que foi enco
Acho que a expressão tá errada... Ela tá redundante, o correto não seria "Além disso, o código que parece limpo está limpo"?

2017-01-31 12:20 UTC, Lucasktrindade commented on chapters/2.Syntax-and-Formatting.md
> +Além disso, o código vai parecer limpo e dar a impresso de estar limpo. É um ecossistema muito melhor para se trabalhar, e faz com que outro membro da equipe mantenha o padrão de limpeza que foi enco
Teria que ser no caso então," dar a impressão de estar limpo".

2017-02-01 21:10 UTC, Lucasktrindade commented
Alterei @gabrielclima, olha ai

2017-02-10 05:32 UTC, gabrielclima approved these changes
Acho que tá de boa

2017-02-10 05:33 UTC, merged