[Para Revisão] - 4. Naming Conventions
GDGDuqueDeCaxias/cssguideline-translate-ptbr pull request #13
Opened 2017-01-21 23:56 UTC by larismourullo

Tradução do trecho do capítulo quatro (**Naming Conventions**) realizada.
@Lucasktrindade @gabrielclima

2017-01-30 19:44 UTC, Lucasktrindade requested changes

2017-01-30 19:44 UTC, Lucasktrindade commented on chapters/4.Naming Conventions.md
> +# Conveções de Nomeclatura
**Convenções

2017-01-30 19:44 UTC, Lucasktrindade commented on chapters/4.Naming Conventions.md
> +Conveções de Nomeclatura em CSS são extremamente úteis para fazer seu código mais estrito, mais transparente e mais informativo.
**Convenções

2017-01-30 19:44 UTC, Lucasktrindade commented on chapters/4.Naming Conventions.md
> +- que (mais) uma classe pode estar relacionada com;
Poderia colocar aqui, 'que (mais) uma classe pode estar relacionada com outra;'

2017-01-30 19:44 UTC, Lucasktrindade commented on chapters/4.Naming Conventions.md
> +A convenção de nomeclatura que sigo é muito simples: hífen (-) delimita strings, com BEM-like nomeando para o mais complexo pedaço de código.
...com BEM-like nomeando para o pedaço de código mais complexo.

2017-01-31 00:06 UTC, larismourullo commented
Corrigido os erros. @Lucasktrindade @gabrielclima

2017-01-31 00:39 UTC, gabrielclima approved these changes
Acho que ficou perfeito

2017-01-31 12:21 UTC, Lucasktrindade approved these changes

2017-01-31 12:21 UTC, merged