Translation cssguideline pt br
GDGDuqueDeCaxias/cssguideline-translate-ptbr pull request #16
Opened 2017-01-31 11:54 UTC by JhonDonavan

Tradução do capitulo 5.iSelector Intent

2017-01-31 11:54 UTC, JhonDonavan commented
@Lucasktrindade 
@gabrielclima

2017-01-31 12:19 UTC, Lucasktrindade commented
@JhonDonavan Vou te pedir pra alterar o nome do PR conforme o guia de contribuição

2017-01-31 15:50 UTC, JhonDonavan commented
@Lucasktrindade nome do PR alterado.

2017-01-31 16:03 UTC, gabrielclima requested changes

2017-01-31 16:03 UTC, gabrielclima commented on chapters/5.CSS Selectors.md
> +no raio de acao que vamos descobrir no nosso CSS, e as dores de cabeça que pode nos trazer.
raio de a**ção**

2017-02-01 11:25 UTC, JhonDonavan commented
@gabrielclima 
@Lucasktrindade 
Fiz a correção solicitada. (Na proxima vou me atentar essa parada da branch)

2017-02-01 14:46 UTC, emanuelgsouza requested changes
No CSS Selectors.md acho interessante mudar a escrita no trecho "um dos aspectos ... " para:
"um dos mais aspectos fundamentais críticos para uma escrita CSS sustentável e escalável são os seletores."

2017-02-01 14:55 UTC, emanuelgsouza requested changes
No Intenção do seletor, dá uma olhada com mais carinho nas frases, como elas estão construídas. Não tenha medo de parafrasear o autor, o importante é que a ideia fique clara para quem for ler o texto.

2017-02-01 20:54 UTC, JhonDonavan commented
@Lucasktrindade @gabrielclima  @emanuelgsouza 
Fiz algumas correções, qualquer coisa, é só avisar.

2017-02-01 21:01 UTC, emanuelgsouza commented on chapters/5.i.Selector Intent.md
> +Intenção do seletor é um processo de decição e definição que você quer para estilo e como voce vai seleciona-lo.
decisão

2017-02-01 21:03 UTC, emanuelgsouza commented on chapters/5.i.Selector Intent.md
> +suas intenções e interfenrindo com conjunto de regras de outra forma não relacionados.
interferindo

2017-02-01 21:16 UTC, emanuelgsouza requested changes
No arquivo Seletores CSS:
* "um dos aspectos fundamentais mais críticos para uma escrita CSS ... "

No arquivo Intenção do seletor:
* palavra decição -- decisão;
* "Por exemplo, se você está querendo um estilo para o menu de navegação ... ";
* incivelmente -- muito;
* "nossa intenção é ... estilizar a ";
* "você pode ter qualquer número de elementos ... ";
* "com seletores ultrapassando suas intenções e interferindo num conjunto de regras de outra forma não relacionados";
* "mas nós podemos mitigar alguns destes defeitos por não escrever isso em seletores que operam globalmente ... "

2017-02-02 11:07 UTC, JhonDonavan commented
@emanuelgsouza 
Fiz as alterações solicitadas.

2017-02-02 12:10 UTC, emanuelgsouza requested changes

2017-02-02 12:10 UTC, emanuelgsouza commented on chapters/5.i.Selector Intent.md
> +Intenção do seletor é um processo de desição e definição que você quer para estilo e como você vai seleciona-lo.
decisão

2017-02-02 12:10 UTC, emanuelgsouza commented on chapters/5.i.Selector Intent.md
> +CSS não pode ser encapsulado, mas nós podemos mitigar alguns destes efeitos por não escrever isso em seletores que operam globalmente
quando eu coloquei: "operam globalmente", já era para substituir o "seletor de operação", saca?

2017-02-02 12:10 UTC, emanuelgsouza commented on chapters/5.i.Selector Intent.md
> +suas intenções e interfenrindo num conjunto de regras de outra forma não relacionados.
interferindo

2017-02-02 12:58 UTC, JhonDonavan commented on chapters/5.i.Selector Intent.md
> +suas intenções e interfenrindo num conjunto de regras de outra forma não relacionados.
Não entendi este comentario.
interferindo?

2017-02-02 13:54 UTC, emanuelgsouza approved these changes

2017-02-04 18:49 UTC, Lucasktrindade commented on chapters/5.i.Selector Intent.md
> +suas intenções e interfenrindo num conjunto de regras de outra forma não relacionados.
Linha 23  ta com erro na escrita da palavra.

2017-02-05 11:32 UTC, JhonDonavan commented on chapters/5.i.Selector Intent.md
> +suas intenções e interfenrindo num conjunto de regras de outra forma não relacionados.
@Lucasktrindade  corrigido.

2017-02-10 05:43 UTC, gabrielclima approved these changes
Só tentar colocar o 
```css
``` 
sempre que tiver um exemplo de código explícito

2017-02-10 05:44 UTC, merged