[Para Revisão] - 2.i. Multiple Files
GDGDuqueDeCaxias/cssguideline-translate-ptbr pull request #18
Opened 2017-02-01 21:41 UTC by Lucasktrindade

2017-02-02 12:12 UTC, emanuelgsouza approved these changes

2017-02-10 05:37 UTC, gabrielclima requested changes

2017-02-10 05:37 UTC, gabrielclima commented on chapters/2.i.Multiple-Files.md
> +Se, por qualquer motivo, você não esteja trabalhando com múltiplos arquivos, as próximas seções podem exigir do seu setup uma adequação.
Não seria "se, por algum motivo, você não _estiver_"?

2017-03-06 15:19 UTC, gabrielclima approved these changes

2017-03-07 01:25 UTC, merged