Create 1.ii.Disclaimers.md
GDGDuqueDeCaxias/cssguideline-translate-ptbr pull request #4
Opened 2016-10-08 05:26 UTC by Lucasktrindade

2016-10-08 05:39 UTC, gabrielclima requested changes

2016-10-08 05:39 UTC, gabrielclima commented on chapters/1.ii.Disclaimers.md
> +*CSS Guidelines* é um guia de estilo, e não é o guia de estilo. O guia contém metodologias, técnicas e dicas que eu com certeza recomendaria aos meus clientes e equipes, porém seus gostos e circunstâ
"porém seus gostos e circunstâncias pode ser diferente"
Não seria mais correto "porém seus gostos e circunstâncias pode**m** ser diferente**s**"? 

:smiley:

2016-10-08 05:41 UTC, Lucasktrindade commented on chapters/1.ii.Disclaimers.md
> +*CSS Guidelines* é um guia de estilo, e não é o guia de estilo. O guia contém metodologias, técnicas e dicas que eu com certeza recomendaria aos meus clientes e equipes, porém seus gostos e circunstâ
Já atualizei

2016-10-08 05:42 UTC, gabrielclima approved these changes
Agora sim!

2016-10-16 01:56 UTC, carolinaknoll commented
Parece bom! 😄 ✨

2016-10-17 00:16 UTC, merged