[Para revisão] - 3.1 - high level
GDGDuqueDeCaxias/cssguideline-translate-ptbr pull request #9
Opened 2016-12-19 12:23 UTC by emanuelgsouza

2017-01-23 16:19 UTC, Lucasktrindade requested changes

2017-01-23 16:19 UTC, Lucasktrindade commented on chapters/3.i.High-level.md
> + * A um cabeçalho de página inicial de um site pode ter dois diferentes estados
O cabeçalho de uma página principal pode ter dois estados diferentes:

2017-01-23 16:19 UTC, Lucasktrindade commented on chapters/3.i.High-level.md
> +Para comentários grandes que documentam seções ou componentes inteiros, nós usamos um *DocBlock-esque* multilinhas que se ajuste à nossa largura de 80 colunas.
... se ajusta à nossa largura de 80 colunas.

2017-01-23 20:57 UTC, emanuelgsouza commented on chapters/3.i.High-level.md
> +Para comentários grandes que documentam seções ou componentes inteiros, nós usamos um *DocBlock-esque* multilinhas que se ajuste à nossa largura de 80 colunas.
Blz, vou ajustar

2017-01-23 20:58 UTC, emanuelgsouza commented on chapters/3.i.High-level.md
> + * A um cabeçalho de página inicial de um site pode ter dois diferentes estados
Desculpa cara, mas não entendi

2017-01-30 19:41 UTC, Lucasktrindade commented on chapters/3.i.High-level.md
> + * A um cabeçalho de página inicial de um site pode ter dois diferentes estados
Semanticamente fica complicado de entender o que você escreveu, por isso coloquei isso, o que acha?

2017-01-30 21:51 UTC, emanuelgsouza commented on chapters/3.i.High-level.md
> +Para comentários grandes que documentam seções ou componentes inteiros, nós usamos um *DocBlock-esque* multilinhas que se ajuste à nossa largura de 80 colunas.
Atualizado, confira o 2° commit.

2017-01-30 22:42 UTC, merged